### PR TITLE
Add twitter link integration

### LINKED ISSUE #52: (Potential Extension) Have bot identify when a transcribed image is a Twitter post and link to the post if possible
**Is your feature request related to a problem? Please describe.**
The bot currently does a good job at transcribing screenshots of Twitter posts. After a successful transcription, people may want to interact with the post on Twitter, and so it would be helpful to have a link to the Tweet if possible (or at least to the Twitter account that made the Tweet).

**Describe the solution you'd like**
The bot should automatically identify whether a transcription is of a Twitter post, and add appropriate hyperlinks.

**Describe alternatives you've considered**
A manual search for the twitter handle or content of the Tweet is possible using a search engine (and is made easier now that the bot successfully transcribes text). However, this process still takes some time, and could be automated.

**Additional context**
This extension has been proposed since day 1 of the project, and so should be worked on earlier.

### PR DESCRIPTION
**Pull request by baconbm**
This PR adds twitter functionality into our bot. If the user adds !Twitter to their textifyreddit request, meaning the image they would like to be transcribed is a twitter post, the bot will search google for the tweet in question. If the bot is unable to find the specific tweet it will look for twitter handles within the tweet and search google for those handles. If the bot is not able to find any twitter links on google it will respond with a message saying it was unsuccessful. This is a somewhat large PR so ask questions if needed. 

This PR also adds two new dependencies - `beautifulsoup4` and `google`. The `requirements.txt` file has been updated to reflect these two new dependencies.

Closes #52

### CODE REVIEW

**Comment by calebeda** [comment]
What happens if there are duplicate tweets? For example, if plagiarism took place and somebody just copied and pasted a tweet and it got really popular, when searching for the tweet, will the bot just pick the top result? If so, maybe we could also confirm that the user of the found tweet is the same user specified by the twitter handle in the transcription.

**Review by calebeda — APPROVED** [review]

**Comment by baconbm** [comment]
Yes, presently the bot picks the top result. I figure if there are enough matches in the search query the top result should be the original tweet. This may become an issue that we need to monitor though.

**Review by afig — APPROVED** [review]
Awesome work @baconbm, looks like plenty of [testing went on](https://www.reddit.com/r/BDFTest/comments/bgk4rx/twitter_link_search_testing/)

**Comment by baconbm** [comment]
You can say that again @afig. Merging now.

**Pull request merged**
