### PR TITLE
Reply to keyword with transcribed text

### PR DESCRIPTION
**Pull request by calebeda**
The bot will now reply to the keyword with the transcribed text from the found image link. But the bot will only do so for the first found keyword to reduce the chance of Reddit flagging the bot for spam. This was done by implementing a Boolean variable that will only allow the bot to reply once after the code is run.

### CODE REVIEW

**Review by baconbm — APPROVED** [review]
Looks good!

**Comment by afig** [comment]
I agree that the solution looks good. However, one small issue I see is that it only replies to requests for comment transcriptions, but not for submission transcriptions. This can be easily addressed by adding another reply statement (again, checked by `checker`) before the `markPostIDAsProcessed` after the `elif isInstance...`.

I also addressed a merge conflict that arose with the merge of PR #35.

**Comment by calebeda** [comment]
Issue has been addressed

**Review by afig — APPROVED** [review]
Looks good! Thanks @calebeda

**Pull request merged**
