### PR TITLE
Add unit testing

### PR DESCRIPTION
**Pull request by baconbm**
This PR represents the initial stages of unit testing for the project. It utilizes the `pytest` unit testing framework. It tests the `extractURL` function and the `tesseractTranscribe` function. These are the most base level functions in or code at the moment. I considered testing the `transcribeImages` and the `findTextInSubreddit` functions, however these presented challenges for unit testing that we may or may not want to address in the future. 

The `findTextInSubreddit` function in particular is challenging to unit test as it requires a connection to reddit and it searches through a specified subreddit for URLs. This is obviously subject to change frequently as more posts are created in the subreddit with more URLs. This will cause issues with our unit testing as we would need to identify and add new images as they are added to the subreddit. An alternative to this would be to create a unit test subreddit that will be mostly static and any changes will be automatically added to our unit tests.

Going forward we should strive to create unit tests for all functions that we create.

### CODE REVIEW

**Review by afig — COMMENTED** [review]
Looks like some files in the `__pycache__` directory were accidentally included in the PR. We should probably remove these to keep the repo clean. We can add the directory to our `.gitignore` to avoid future issues.

Otherwise, the solution looks good. Thanks @baconbm. In terms of `findTextInSubreddit`, I agree that it will be hard to unit test. Opening up a subreddit for unit tests is a possibility. but it will actually might not work in the future due to the new method of identifying posts to parse. We will have to consider what options we have later.

**Review by afig — APPROVED** [review]
Looks good to merge

**Review by calebeda — APPROVED** [review]
Looks good to go

**Comment by baconbm** [comment]
Closes Issue #25

**Pull request merged**
