### PR TITLE
Add BranchStrategy Doc

### PR DESCRIPTION
**Pull request by baconbm**
Added a docs folder and added BranchingStrategy.docx document within it.

### CODE REVIEW

**Comment by afig** [comment]
Looks like a Microsoft office hidden file (starting with `~`) was also included in the PR. I would recommend removing it to avoid confusion and any potential errors when opening the file later.

**Comment by baconbm** [comment]
Ok, I've deleted the hidden file, thanks for the note @afig

**Review by afig — APPROVED** [review]
Looks good to merge. Thanks @baconbm for adding this document to the repo.

**Review by calebeda — APPROVED** [review]
Looks good to me

**Pull request merged**
