### PR TITLE
add parameterized extractUsername unit tests

### LINKED ISSUE #88: No unit test exists for `extractUsername`
**Describe the bug**
We currently are not unit testing a candidate unit test function, `extractUsername`. We should be unit testing all functions where it makes sense to do so.

**To Reproduce**
1. Go to `/tests/test_textifyBot.py`
2. See `extractUsername` does not have associated unit tests

**Expected behavior**
`unitTest` is unit tested with all test cases

### PR DESCRIPTION
**Pull request by baconbm**
This PR adds unit tests for the `extractUsername` function. You will also code to remove an unnecessary else. This is being addressed in another PR but I needed it for the code to run on my local so feel free to disregard. Closes #88

### CODE REVIEW

**Comment by calebeda** [comment]
Is it supposed to be ‘extractUsername’?

**Comment by baconbm** [comment]
oops. yes, thanks.

**Comment by calebeda** [comment]
Thanks @baconbm , now no twitter username can escape our grasp! (Until proven wrong)

**Review by calebeda — APPROVED** [review]

**Review by afig — APPROVED** [review]
Looks good to merge. Thanks

**Pull request merged**
